# Generated by Django 2.1.2 on 2018-11-01 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 3, 4, 14, 190515)),
        ),
    ]
